//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cltCropland complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cltCropland">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="guid" type="{http://ipcc2006.air.sk/IPCC2006Export}guid"/>
 *         &lt;element name="countryCode" type="{http://ipcc2006.air.sk/IPCC2006Export}countryCode"/>
 *         &lt;element name="customName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="climateRegionId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilStatusId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="nutrientTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="perennialCrops" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="croplandTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="croplandTypeCustom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="riceEcosystem" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mfLandUse" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfTillage" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfInput" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="harvestCycle" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bWoody" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bWoodyAccumulationRate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bWoodyUnitId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bWoodyCFrac" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ratioBgbAgbWoody" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ageClassId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bHerb" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bHerbUnitId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bHerbCFrac" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ageClassValue" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="agroforestry" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ratioBgbAgbHerb" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="soilCarbonStock" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cltCropland", propOrder = {
    "id",
    "guid",
    "countryCode",
    "customName",
    "climateRegionId",
    "soilTypeId",
    "soilStatusId",
    "nutrientTypeId",
    "perennialCrops",
    "croplandTypeId",
    "croplandTypeCustom",
    "riceEcosystem",
    "mfLandUse",
    "mfTillage",
    "mfInput",
    "harvestCycle",
    "bWoody",
    "bWoodyAccumulationRate",
    "bWoodyUnitId",
    "bWoodyCFrac",
    "ratioBgbAgbWoody",
    "ageClassId",
    "bHerb",
    "bHerbUnitId",
    "bHerbCFrac",
    "ageClassValue",
    "agroforestry",
    "ratioBgbAgbHerb",
    "soilCarbonStock"
})
public class CltCropland {

    @XmlElement(required = true)
    protected Integer id;
    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected String customName;
    @XmlElement(required = true)
    protected Integer climateRegionId;
    @XmlElement(required = true)
    protected Integer soilTypeId;
    @XmlElement(required = true)
    protected Integer soilStatusId;
    @XmlElement(required = true)
    protected Integer nutrientTypeId;
    protected boolean perennialCrops;
    @XmlElement(required = true)
    protected Integer croplandTypeId;
    @XmlElement(required = true, nillable = true)
    protected String croplandTypeCustom;
    protected boolean riceEcosystem;
    protected double mfLandUse;
    protected double mfTillage;
    protected double mfInput;
    protected double harvestCycle;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bWoody;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bWoodyAccumulationRate;
    @XmlElement(required = true)
    protected Integer bWoodyUnitId;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bWoodyCFrac;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ratioBgbAgbWoody;
    @XmlElement(required = true)
    protected Integer ageClassId;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bHerb;
    @XmlElement(required = true)
    protected Integer bHerbUnitId;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bHerbCFrac;
    @XmlElement(required = true, nillable = true)
    protected Integer ageClassValue;
    protected boolean agroforestry;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ratioBgbAgbHerb;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double soilCarbonStock;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the customName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * Sets the value of the customName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomName(String value) {
        this.customName = value;
    }

    /**
     * Gets the value of the climateRegionId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClimateRegionId() {
        return climateRegionId;
    }

    /**
     * Sets the value of the climateRegionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClimateRegionId(Integer value) {
        this.climateRegionId = value;
    }

    /**
     * Gets the value of the soilTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSoilTypeId() {
        return soilTypeId;
    }

    /**
     * Sets the value of the soilTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSoilTypeId(Integer value) {
        this.soilTypeId = value;
    }

    /**
     * Gets the value of the soilStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSoilStatusId() {
        return soilStatusId;
    }

    /**
     * Sets the value of the soilStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSoilStatusId(Integer value) {
        this.soilStatusId = value;
    }

    /**
     * Gets the value of the nutrientTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNutrientTypeId() {
        return nutrientTypeId;
    }

    /**
     * Sets the value of the nutrientTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNutrientTypeId(Integer value) {
        this.nutrientTypeId = value;
    }

    /**
     * Gets the value of the perennialCrops property.
     * 
     */
    public boolean isPerennialCrops() {
        return perennialCrops;
    }

    /**
     * Sets the value of the perennialCrops property.
     * 
     */
    public void setPerennialCrops(boolean value) {
        this.perennialCrops = value;
    }

    /**
     * Gets the value of the croplandTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCroplandTypeId() {
        return croplandTypeId;
    }

    /**
     * Sets the value of the croplandTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCroplandTypeId(Integer value) {
        this.croplandTypeId = value;
    }

    /**
     * Gets the value of the croplandTypeCustom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCroplandTypeCustom() {
        return croplandTypeCustom;
    }

    /**
     * Sets the value of the croplandTypeCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCroplandTypeCustom(String value) {
        this.croplandTypeCustom = value;
    }

    /**
     * Gets the value of the riceEcosystem property.
     * 
     */
    public boolean isRiceEcosystem() {
        return riceEcosystem;
    }

    /**
     * Sets the value of the riceEcosystem property.
     * 
     */
    public void setRiceEcosystem(boolean value) {
        this.riceEcosystem = value;
    }

    /**
     * Gets the value of the mfLandUse property.
     * 
     */
    public double getMfLandUse() {
        return mfLandUse;
    }

    /**
     * Sets the value of the mfLandUse property.
     * 
     */
    public void setMfLandUse(double value) {
        this.mfLandUse = value;
    }

    /**
     * Gets the value of the mfTillage property.
     * 
     */
    public double getMfTillage() {
        return mfTillage;
    }

    /**
     * Sets the value of the mfTillage property.
     * 
     */
    public void setMfTillage(double value) {
        this.mfTillage = value;
    }

    /**
     * Gets the value of the mfInput property.
     * 
     */
    public double getMfInput() {
        return mfInput;
    }

    /**
     * Sets the value of the mfInput property.
     * 
     */
    public void setMfInput(double value) {
        this.mfInput = value;
    }

    /**
     * Gets the value of the harvestCycle property.
     * 
     */
    public double getHarvestCycle() {
        return harvestCycle;
    }

    /**
     * Sets the value of the harvestCycle property.
     * 
     */
    public void setHarvestCycle(double value) {
        this.harvestCycle = value;
    }

    /**
     * Gets the value of the bWoody property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBWoody() {
        return bWoody;
    }

    /**
     * Sets the value of the bWoody property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBWoody(Double value) {
        this.bWoody = value;
    }

    /**
     * Gets the value of the bWoodyAccumulationRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBWoodyAccumulationRate() {
        return bWoodyAccumulationRate;
    }

    /**
     * Sets the value of the bWoodyAccumulationRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBWoodyAccumulationRate(Double value) {
        this.bWoodyAccumulationRate = value;
    }

    /**
     * Gets the value of the bWoodyUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBWoodyUnitId() {
        return bWoodyUnitId;
    }

    /**
     * Sets the value of the bWoodyUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBWoodyUnitId(Integer value) {
        this.bWoodyUnitId = value;
    }

    /**
     * Gets the value of the bWoodyCFrac property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBWoodyCFrac() {
        return bWoodyCFrac;
    }

    /**
     * Sets the value of the bWoodyCFrac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBWoodyCFrac(Double value) {
        this.bWoodyCFrac = value;
    }

    /**
     * Gets the value of the ratioBgbAgbWoody property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRatioBgbAgbWoody() {
        return ratioBgbAgbWoody;
    }

    /**
     * Sets the value of the ratioBgbAgbWoody property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRatioBgbAgbWoody(Double value) {
        this.ratioBgbAgbWoody = value;
    }

    /**
     * Gets the value of the ageClassId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgeClassId() {
        return ageClassId;
    }

    /**
     * Sets the value of the ageClassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgeClassId(Integer value) {
        this.ageClassId = value;
    }

    /**
     * Gets the value of the bHerb property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBHerb() {
        return bHerb;
    }

    /**
     * Sets the value of the bHerb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBHerb(Double value) {
        this.bHerb = value;
    }

    /**
     * Gets the value of the bHerbUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBHerbUnitId() {
        return bHerbUnitId;
    }

    /**
     * Sets the value of the bHerbUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBHerbUnitId(Integer value) {
        this.bHerbUnitId = value;
    }

    /**
     * Gets the value of the bHerbCFrac property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBHerbCFrac() {
        return bHerbCFrac;
    }

    /**
     * Sets the value of the bHerbCFrac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBHerbCFrac(Double value) {
        this.bHerbCFrac = value;
    }

    /**
     * Gets the value of the ageClassValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgeClassValue() {
        return ageClassValue;
    }

    /**
     * Sets the value of the ageClassValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgeClassValue(Integer value) {
        this.ageClassValue = value;
    }

    /**
     * Gets the value of the agroforestry property.
     * 
     */
    public boolean isAgroforestry() {
        return agroforestry;
    }

    /**
     * Sets the value of the agroforestry property.
     * 
     */
    public void setAgroforestry(boolean value) {
        this.agroforestry = value;
    }

    /**
     * Gets the value of the ratioBgbAgbHerb property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRatioBgbAgbHerb() {
        return ratioBgbAgbHerb;
    }

    /**
     * Sets the value of the ratioBgbAgbHerb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRatioBgbAgbHerb(Double value) {
        this.ratioBgbAgbHerb = value;
    }

    /**
     * Gets the value of the soilCarbonStock property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSoilCarbonStock() {
        return soilCarbonStock;
    }

    /**
     * Sets the value of the soilCarbonStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSoilCarbonStock(Double value) {
        this.soilCarbonStock = value;
    }

}
