//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cltForestLand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cltForestLand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="guid" type="{http://ipcc2006.air.sk/IPCC2006Export}guid"/>
 *         &lt;element name="customName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="managed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="climateRegionId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilStatusId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="nutrientTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ecoZoneId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ecoZoneCustom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plantation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="forestTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="forestTypeCustom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="continentTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ageClassId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="growingStockLevelId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="carbonFraction" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ratio" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bcefRType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bcefR" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="aboveGroundBiomass" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="aboveGroundBiomassGrowth" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfLandUse" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfTillage" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfInput" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="abandoned" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="woodDensity" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="growingStockInc" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bcefIType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bef1" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bcefI" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bcefSType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bef2" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bcefS" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ageClassRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="growingStockLevelValue" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilCarbonStock" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cltForestLand", propOrder = {
    "id",
    "guid",
    "customName",
    "managed",
    "climateRegionId",
    "soilTypeId",
    "soilStatusId",
    "nutrientTypeId",
    "ecoZoneId",
    "ecoZoneCustom",
    "plantation",
    "forestTypeId",
    "forestTypeCustom",
    "continentTypeId",
    "ageClassId",
    "growingStockLevelId",
    "carbonFraction",
    "ratio",
    "bcefRType",
    "bcefR",
    "aboveGroundBiomass",
    "aboveGroundBiomassGrowth",
    "mfLandUse",
    "mfTillage",
    "mfInput",
    "abandoned",
    "woodDensity",
    "growingStockInc",
    "bcefIType",
    "bef1",
    "bcefI",
    "bcefSType",
    "bef2",
    "bcefS",
    "ageClassRange",
    "growingStockLevelValue",
    "soilCarbonStock"
})
public class CltForestLand {

    @XmlElement(required = true)
    protected Integer id;
    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected String customName;
    protected boolean managed;
    @XmlElement(required = true)
    protected Integer climateRegionId;
    @XmlElement(required = true)
    protected Integer soilTypeId;
    @XmlElement(required = true)
    protected Integer soilStatusId;
    @XmlElement(required = true)
    protected Integer nutrientTypeId;
    @XmlElement(required = true)
    protected Integer ecoZoneId;
    @XmlElement(required = true, nillable = true)
    protected String ecoZoneCustom;
    protected boolean plantation;
    @XmlElement(required = true)
    protected Integer forestTypeId;
    @XmlElement(required = true, nillable = true)
    protected String forestTypeCustom;
    @XmlElement(required = true)
    protected Integer continentTypeId;
    @XmlElement(required = true)
    protected Integer ageClassId;
    @XmlElement(required = true)
    protected Integer growingStockLevelId;
    protected double carbonFraction;
    protected double ratio;
    @XmlElement(required = true)
    protected Integer bcefRType;
    protected double bcefR;
    protected double aboveGroundBiomass;
    protected double aboveGroundBiomassGrowth;
    protected double mfLandUse;
    protected double mfTillage;
    protected double mfInput;
    protected boolean abandoned;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double woodDensity;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double growingStockInc;
    @XmlElement(required = true)
    protected Integer bcefIType;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bef1;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bcefI;
    @XmlElement(required = true)
    protected Integer bcefSType;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bef2;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double bcefS;
    @XmlElement(required = true, nillable = true)
    protected String ageClassRange;
    @XmlElement(required = true, nillable = true)
    protected Integer growingStockLevelValue;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double soilCarbonStock;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the customName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * Sets the value of the customName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomName(String value) {
        this.customName = value;
    }

    /**
     * Gets the value of the managed property.
     * 
     */
    public boolean isManaged() {
        return managed;
    }

    /**
     * Sets the value of the managed property.
     * 
     */
    public void setManaged(boolean value) {
        this.managed = value;
    }

    /**
     * Gets the value of the climateRegionId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClimateRegionId() {
        return climateRegionId;
    }

    /**
     * Sets the value of the climateRegionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClimateRegionId(Integer value) {
        this.climateRegionId = value;
    }

    /**
     * Gets the value of the soilTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSoilTypeId() {
        return soilTypeId;
    }

    /**
     * Sets the value of the soilTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSoilTypeId(Integer value) {
        this.soilTypeId = value;
    }

    /**
     * Gets the value of the soilStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSoilStatusId() {
        return soilStatusId;
    }

    /**
     * Sets the value of the soilStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSoilStatusId(Integer value) {
        this.soilStatusId = value;
    }

    /**
     * Gets the value of the nutrientTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNutrientTypeId() {
        return nutrientTypeId;
    }

    /**
     * Sets the value of the nutrientTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNutrientTypeId(Integer value) {
        this.nutrientTypeId = value;
    }

    /**
     * Gets the value of the ecoZoneId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEcoZoneId() {
        return ecoZoneId;
    }

    /**
     * Sets the value of the ecoZoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEcoZoneId(Integer value) {
        this.ecoZoneId = value;
    }

    /**
     * Gets the value of the ecoZoneCustom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcoZoneCustom() {
        return ecoZoneCustom;
    }

    /**
     * Sets the value of the ecoZoneCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcoZoneCustom(String value) {
        this.ecoZoneCustom = value;
    }

    /**
     * Gets the value of the plantation property.
     * 
     */
    public boolean isPlantation() {
        return plantation;
    }

    /**
     * Sets the value of the plantation property.
     * 
     */
    public void setPlantation(boolean value) {
        this.plantation = value;
    }

    /**
     * Gets the value of the forestTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getForestTypeId() {
        return forestTypeId;
    }

    /**
     * Sets the value of the forestTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setForestTypeId(Integer value) {
        this.forestTypeId = value;
    }

    /**
     * Gets the value of the forestTypeCustom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForestTypeCustom() {
        return forestTypeCustom;
    }

    /**
     * Sets the value of the forestTypeCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForestTypeCustom(String value) {
        this.forestTypeCustom = value;
    }

    /**
     * Gets the value of the continentTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getContinentTypeId() {
        return continentTypeId;
    }

    /**
     * Sets the value of the continentTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setContinentTypeId(Integer value) {
        this.continentTypeId = value;
    }

    /**
     * Gets the value of the ageClassId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgeClassId() {
        return ageClassId;
    }

    /**
     * Sets the value of the ageClassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgeClassId(Integer value) {
        this.ageClassId = value;
    }

    /**
     * Gets the value of the growingStockLevelId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrowingStockLevelId() {
        return growingStockLevelId;
    }

    /**
     * Sets the value of the growingStockLevelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrowingStockLevelId(Integer value) {
        this.growingStockLevelId = value;
    }

    /**
     * Gets the value of the carbonFraction property.
     * 
     */
    public double getCarbonFraction() {
        return carbonFraction;
    }

    /**
     * Sets the value of the carbonFraction property.
     * 
     */
    public void setCarbonFraction(double value) {
        this.carbonFraction = value;
    }

    /**
     * Gets the value of the ratio property.
     * 
     */
    public double getRatio() {
        return ratio;
    }

    /**
     * Sets the value of the ratio property.
     * 
     */
    public void setRatio(double value) {
        this.ratio = value;
    }

    /**
     * Gets the value of the bcefRType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBcefRType() {
        return bcefRType;
    }

    /**
     * Sets the value of the bcefRType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBcefRType(Integer value) {
        this.bcefRType = value;
    }

    /**
     * Gets the value of the bcefR property.
     * 
     */
    public double getBcefR() {
        return bcefR;
    }

    /**
     * Sets the value of the bcefR property.
     * 
     */
    public void setBcefR(double value) {
        this.bcefR = value;
    }

    /**
     * Gets the value of the aboveGroundBiomass property.
     * 
     */
    public double getAboveGroundBiomass() {
        return aboveGroundBiomass;
    }

    /**
     * Sets the value of the aboveGroundBiomass property.
     * 
     */
    public void setAboveGroundBiomass(double value) {
        this.aboveGroundBiomass = value;
    }

    /**
     * Gets the value of the aboveGroundBiomassGrowth property.
     * 
     */
    public double getAboveGroundBiomassGrowth() {
        return aboveGroundBiomassGrowth;
    }

    /**
     * Sets the value of the aboveGroundBiomassGrowth property.
     * 
     */
    public void setAboveGroundBiomassGrowth(double value) {
        this.aboveGroundBiomassGrowth = value;
    }

    /**
     * Gets the value of the mfLandUse property.
     * 
     */
    public double getMfLandUse() {
        return mfLandUse;
    }

    /**
     * Sets the value of the mfLandUse property.
     * 
     */
    public void setMfLandUse(double value) {
        this.mfLandUse = value;
    }

    /**
     * Gets the value of the mfTillage property.
     * 
     */
    public double getMfTillage() {
        return mfTillage;
    }

    /**
     * Sets the value of the mfTillage property.
     * 
     */
    public void setMfTillage(double value) {
        this.mfTillage = value;
    }

    /**
     * Gets the value of the mfInput property.
     * 
     */
    public double getMfInput() {
        return mfInput;
    }

    /**
     * Sets the value of the mfInput property.
     * 
     */
    public void setMfInput(double value) {
        this.mfInput = value;
    }

    /**
     * Gets the value of the abandoned property.
     * 
     */
    public boolean isAbandoned() {
        return abandoned;
    }

    /**
     * Sets the value of the abandoned property.
     * 
     */
    public void setAbandoned(boolean value) {
        this.abandoned = value;
    }

    /**
     * Gets the value of the woodDensity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWoodDensity() {
        return woodDensity;
    }

    /**
     * Sets the value of the woodDensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWoodDensity(Double value) {
        this.woodDensity = value;
    }

    /**
     * Gets the value of the growingStockInc property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getGrowingStockInc() {
        return growingStockInc;
    }

    /**
     * Sets the value of the growingStockInc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setGrowingStockInc(Double value) {
        this.growingStockInc = value;
    }

    /**
     * Gets the value of the bcefIType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBcefIType() {
        return bcefIType;
    }

    /**
     * Sets the value of the bcefIType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBcefIType(Integer value) {
        this.bcefIType = value;
    }

    /**
     * Gets the value of the bef1 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBef1() {
        return bef1;
    }

    /**
     * Sets the value of the bef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBef1(Double value) {
        this.bef1 = value;
    }

    /**
     * Gets the value of the bcefI property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBcefI() {
        return bcefI;
    }

    /**
     * Sets the value of the bcefI property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBcefI(Double value) {
        this.bcefI = value;
    }

    /**
     * Gets the value of the bcefSType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBcefSType() {
        return bcefSType;
    }

    /**
     * Sets the value of the bcefSType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBcefSType(Integer value) {
        this.bcefSType = value;
    }

    /**
     * Gets the value of the bef2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBef2() {
        return bef2;
    }

    /**
     * Sets the value of the bef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBef2(Double value) {
        this.bef2 = value;
    }

    /**
     * Gets the value of the bcefS property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBcefS() {
        return bcefS;
    }

    /**
     * Sets the value of the bcefS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBcefS(Double value) {
        this.bcefS = value;
    }

    /**
     * Gets the value of the ageClassRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeClassRange() {
        return ageClassRange;
    }

    /**
     * Sets the value of the ageClassRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeClassRange(String value) {
        this.ageClassRange = value;
    }

    /**
     * Gets the value of the growingStockLevelValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrowingStockLevelValue() {
        return growingStockLevelValue;
    }

    /**
     * Sets the value of the growingStockLevelValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrowingStockLevelValue(Integer value) {
        this.growingStockLevelValue = value;
    }

    /**
     * Gets the value of the soilCarbonStock property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSoilCarbonStock() {
        return soilCarbonStock;
    }

    /**
     * Sets the value of the soilCarbonStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSoilCarbonStock(Double value) {
        this.soilCarbonStock = value;
    }

}
