//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.22 at 11:25:06 AM CET 
//


package org.openforis.collect.earth.ipcc.serialize;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cltOtherland complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cltOtherland">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="guid" type="{http://ipcc2006.air.sk/IPCC2006Export}guid"/>
 *         &lt;element name="countryCode" type="{http://ipcc2006.air.sk/IPCC2006Export}countryCode"/>
 *         &lt;element name="customName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="managed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="climateRegionId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="geoPlacementId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="nutrientTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cltOtherland", propOrder = {
    "id",
    "guid",
    "countryCode",
    "customName",
    "managed",
    "climateRegionId",
    "soilTypeId",
    "geoPlacementId",
    "nutrientTypeId"
})
public class CltOtherland {

    @XmlElement(required = true)
    protected Integer id;
    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected String customName;
    protected boolean managed;
    @XmlElement(required = true)
    protected Integer climateRegionId;
    @XmlElement(required = true)
    protected Integer soilTypeId;
    @XmlElement(required = true)
    protected Integer geoPlacementId;
    @XmlElement(required = true)
    protected Integer nutrientTypeId;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the customName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * Sets the value of the customName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomName(String value) {
        this.customName = value;
    }

    /**
     * Gets the value of the managed property.
     * 
     */
    public boolean isManaged() {
        return managed;
    }

    /**
     * Sets the value of the managed property.
     * 
     */
    public void setManaged(boolean value) {
        this.managed = value;
    }

    /**
     * Gets the value of the climateRegionId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClimateRegionId() {
        return climateRegionId;
    }

    /**
     * Sets the value of the climateRegionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClimateRegionId(Integer value) {
        this.climateRegionId = value;
    }

    /**
     * Gets the value of the soilTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSoilTypeId() {
        return soilTypeId;
    }

    /**
     * Sets the value of the soilTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSoilTypeId(Integer value) {
        this.soilTypeId = value;
    }

    /**
     * Gets the value of the geoPlacementId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGeoPlacementId() {
        return geoPlacementId;
    }

    /**
     * Sets the value of the geoPlacementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGeoPlacementId(Integer value) {
        this.geoPlacementId = value;
    }

    /**
     * Gets the value of the nutrientTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNutrientTypeId() {
        return nutrientTypeId;
    }

    /**
     * Sets the value of the nutrientTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNutrientTypeId(Integer value) {
        this.nutrientTypeId = value;
    }

}
