//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cltSettlement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cltSettlement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="guid" type="{http://ipcc2006.air.sk/IPCC2006Export}guid"/>
 *         &lt;element name="countryCode" type="{http://ipcc2006.air.sk/IPCC2006Export}countryCode"/>
 *         &lt;element name="customName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="climateRegionId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilStatusId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="nutrientTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="settlementTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="mfLandUse" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfTillage" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfInput" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="biomassStock" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="carbonFraction" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ratioBgbAgb" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ageClassId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="agp" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="propCult" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfLandUseCult" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfManagCult" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfInputCult" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="propTurfgrass" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfLandUseTurfgrass" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfManagTurfgrass" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfInputTurfgrass" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="propPaved" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfLandUsePaved" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfManagPaved" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mfInputPaved" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="soilCarbonStock" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="numberOfClasses" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cltSettlement", propOrder = {
    "id",
    "guid",
    "countryCode",
    "customName",
    "climateRegionId",
    "soilTypeId",
    "soilStatusId",
    "nutrientTypeId",
    "settlementTypeId",
    "mfLandUse",
    "mfTillage",
    "mfInput",
    "biomassStock",
    "carbonFraction",
    "ratioBgbAgb",
    "ageClassId",
    "agp",
    "propCult",
    "mfLandUseCult",
    "mfManagCult",
    "mfInputCult",
    "propTurfgrass",
    "mfLandUseTurfgrass",
    "mfManagTurfgrass",
    "mfInputTurfgrass",
    "propPaved",
    "mfLandUsePaved",
    "mfManagPaved",
    "mfInputPaved",
    "soilCarbonStock",
    "numberOfClasses"
})
public class CltSettlement {

    @XmlElement(required = true)
    protected Integer id;
    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected String customName;
    @XmlElement(required = true)
    protected Integer climateRegionId;
    @XmlElement(required = true)
    protected Integer soilTypeId;
    @XmlElement(required = true)
    protected Integer soilStatusId;
    @XmlElement(required = true)
    protected Integer nutrientTypeId;
    @XmlElement(required = true)
    protected Integer settlementTypeId;
    protected double mfLandUse;
    protected double mfTillage;
    protected double mfInput;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double biomassStock;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double carbonFraction;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ratioBgbAgb;
    @XmlElement(required = true)
    protected Integer ageClassId;
    @XmlElement(required = true, nillable = true)
    protected Integer agp;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double propCult;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfLandUseCult;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfManagCult;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfInputCult;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double propTurfgrass;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfLandUseTurfgrass;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfManagTurfgrass;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfInputTurfgrass;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double propPaved;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfLandUsePaved;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfManagPaved;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double mfInputPaved;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double soilCarbonStock;
    @XmlElement(required = true)
    protected Integer numberOfClasses;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the customName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * Sets the value of the customName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomName(String value) {
        this.customName = value;
    }

    /**
     * Gets the value of the climateRegionId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClimateRegionId() {
        return climateRegionId;
    }

    /**
     * Sets the value of the climateRegionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClimateRegionId(Integer value) {
        this.climateRegionId = value;
    }

    /**
     * Gets the value of the soilTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSoilTypeId() {
        return soilTypeId;
    }

    /**
     * Sets the value of the soilTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSoilTypeId(Integer value) {
        this.soilTypeId = value;
    }

    /**
     * Gets the value of the soilStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSoilStatusId() {
        return soilStatusId;
    }

    /**
     * Sets the value of the soilStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSoilStatusId(Integer value) {
        this.soilStatusId = value;
    }

    /**
     * Gets the value of the nutrientTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNutrientTypeId() {
        return nutrientTypeId;
    }

    /**
     * Sets the value of the nutrientTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNutrientTypeId(Integer value) {
        this.nutrientTypeId = value;
    }

    /**
     * Gets the value of the settlementTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSettlementTypeId() {
        return settlementTypeId;
    }

    /**
     * Sets the value of the settlementTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSettlementTypeId(Integer value) {
        this.settlementTypeId = value;
    }

    /**
     * Gets the value of the mfLandUse property.
     * 
     */
    public double getMfLandUse() {
        return mfLandUse;
    }

    /**
     * Sets the value of the mfLandUse property.
     * 
     */
    public void setMfLandUse(double value) {
        this.mfLandUse = value;
    }

    /**
     * Gets the value of the mfTillage property.
     * 
     */
    public double getMfTillage() {
        return mfTillage;
    }

    /**
     * Sets the value of the mfTillage property.
     * 
     */
    public void setMfTillage(double value) {
        this.mfTillage = value;
    }

    /**
     * Gets the value of the mfInput property.
     * 
     */
    public double getMfInput() {
        return mfInput;
    }

    /**
     * Sets the value of the mfInput property.
     * 
     */
    public void setMfInput(double value) {
        this.mfInput = value;
    }

    /**
     * Gets the value of the biomassStock property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBiomassStock() {
        return biomassStock;
    }

    /**
     * Sets the value of the biomassStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBiomassStock(Double value) {
        this.biomassStock = value;
    }

    /**
     * Gets the value of the carbonFraction property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCarbonFraction() {
        return carbonFraction;
    }

    /**
     * Sets the value of the carbonFraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCarbonFraction(Double value) {
        this.carbonFraction = value;
    }

    /**
     * Gets the value of the ratioBgbAgb property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRatioBgbAgb() {
        return ratioBgbAgb;
    }

    /**
     * Sets the value of the ratioBgbAgb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRatioBgbAgb(Double value) {
        this.ratioBgbAgb = value;
    }

    /**
     * Gets the value of the ageClassId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgeClassId() {
        return ageClassId;
    }

    /**
     * Sets the value of the ageClassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgeClassId(Integer value) {
        this.ageClassId = value;
    }

    /**
     * Gets the value of the agp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgp() {
        return agp;
    }

    /**
     * Sets the value of the agp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgp(Integer value) {
        this.agp = value;
    }

    /**
     * Gets the value of the propCult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPropCult() {
        return propCult;
    }

    /**
     * Sets the value of the propCult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPropCult(Double value) {
        this.propCult = value;
    }

    /**
     * Gets the value of the mfLandUseCult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfLandUseCult() {
        return mfLandUseCult;
    }

    /**
     * Sets the value of the mfLandUseCult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfLandUseCult(Double value) {
        this.mfLandUseCult = value;
    }

    /**
     * Gets the value of the mfManagCult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfManagCult() {
        return mfManagCult;
    }

    /**
     * Sets the value of the mfManagCult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfManagCult(Double value) {
        this.mfManagCult = value;
    }

    /**
     * Gets the value of the mfInputCult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfInputCult() {
        return mfInputCult;
    }

    /**
     * Sets the value of the mfInputCult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfInputCult(Double value) {
        this.mfInputCult = value;
    }

    /**
     * Gets the value of the propTurfgrass property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPropTurfgrass() {
        return propTurfgrass;
    }

    /**
     * Sets the value of the propTurfgrass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPropTurfgrass(Double value) {
        this.propTurfgrass = value;
    }

    /**
     * Gets the value of the mfLandUseTurfgrass property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfLandUseTurfgrass() {
        return mfLandUseTurfgrass;
    }

    /**
     * Sets the value of the mfLandUseTurfgrass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfLandUseTurfgrass(Double value) {
        this.mfLandUseTurfgrass = value;
    }

    /**
     * Gets the value of the mfManagTurfgrass property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfManagTurfgrass() {
        return mfManagTurfgrass;
    }

    /**
     * Sets the value of the mfManagTurfgrass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfManagTurfgrass(Double value) {
        this.mfManagTurfgrass = value;
    }

    /**
     * Gets the value of the mfInputTurfgrass property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfInputTurfgrass() {
        return mfInputTurfgrass;
    }

    /**
     * Sets the value of the mfInputTurfgrass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfInputTurfgrass(Double value) {
        this.mfInputTurfgrass = value;
    }

    /**
     * Gets the value of the propPaved property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPropPaved() {
        return propPaved;
    }

    /**
     * Sets the value of the propPaved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPropPaved(Double value) {
        this.propPaved = value;
    }

    /**
     * Gets the value of the mfLandUsePaved property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfLandUsePaved() {
        return mfLandUsePaved;
    }

    /**
     * Sets the value of the mfLandUsePaved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfLandUsePaved(Double value) {
        this.mfLandUsePaved = value;
    }

    /**
     * Gets the value of the mfManagPaved property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfManagPaved() {
        return mfManagPaved;
    }

    /**
     * Sets the value of the mfManagPaved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfManagPaved(Double value) {
        this.mfManagPaved = value;
    }

    /**
     * Gets the value of the mfInputPaved property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMfInputPaved() {
        return mfInputPaved;
    }

    /**
     * Sets the value of the mfInputPaved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMfInputPaved(Double value) {
        this.mfInputPaved = value;
    }

    /**
     * Gets the value of the soilCarbonStock property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSoilCarbonStock() {
        return soilCarbonStock;
    }

    /**
     * Sets the value of the soilCarbonStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSoilCarbonStock(Double value) {
        this.soilCarbonStock = value;
    }

    /**
     * Gets the value of the numberOfClasses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfClasses() {
        return numberOfClasses;
    }

    /**
     * Sets the value of the numberOfClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfClasses(Integer value) {
        this.numberOfClasses = value;
    }

}
