//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.22 at 11:25:06 AM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ipccSubdivision complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ipccSubdivision">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://ipcc2006.air.sk/IPCC2006Export}guid"/>
 *         &lt;element name="ipccCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subdivision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isFixed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ipccSubdivision", propOrder = {
    "id",
    "ipccCode",
    "subdivision",
    "isFixed"
})
public class IpccSubdivision {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String ipccCode;
    @XmlElement(required = true)
    protected String subdivision;
    protected boolean isFixed;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the ipccCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpccCode() {
        return ipccCode;
    }

    /**
     * Sets the value of the ipccCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpccCode(String value) {
        this.ipccCode = value;
    }

    /**
     * Gets the value of the subdivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubdivision() {
        return subdivision;
    }

    /**
     * Sets the value of the subdivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubdivision(String value) {
        this.subdivision = value;
    }

    /**
     * Gets the value of the isFixed property.
     * 
     */
    public boolean isIsFixed() {
        return isFixed;
    }

    /**
     * Sets the value of the isFixed property.
     * 
     */
    public void setIsFixed(boolean value) {
        this.isFixed = value;
    }

}
