//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "signature"
})
@XmlRootElement(name = "IPCC2006Export")
public class IPCC2006ExportSigned extends IPCC2006Export{

    @XmlElement(name = "signature", required = true)
    protected String signature;

    public static IPCC2006ExportSigned cloneAndSign( IPCC2006Export notSigned, String signature ) {
    	IPCC2006ExportSigned signed = new IPCC2006ExportSigned();
    	signed.setCountryCode( notSigned.getCountryCode());
    	signed.setInventoryYear( notSigned.getInventoryYear());
    	signed.setVersion( notSigned.getVersion());
    	signed.record = notSigned.record;
        signed.setSignature(signature);
        return signed;
     }

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}
}
