//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for landRepresentation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="landRepresentation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lrtCountry" type="{http://ipcc2006.air.sk/IPCC2006Export}lrtCountry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "landRepresentation", propOrder = {
    "lrtCountry"
})
public class LandRepresentation {

    @XmlElement(required = true)
    protected LrtCountry lrtCountry;

    /**
     * Gets the value of the lrtCountry property.
     * 
     * @return
     *     possible object is
     *     {@link LrtCountry }
     *     
     */
    public LrtCountry getLrtCountry() {
        return lrtCountry;
    }

    /**
     * Sets the value of the lrtCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link LrtCountry }
     *     
     */
    public void setLrtCountry(LrtCountry value) {
        this.lrtCountry = value;
    }

}
