//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.22 at 11:25:06 AM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for landTypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="landTypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="countryCode" type="{http://ipcc2006.air.sk/IPCC2006Export}countryCode"/>
 *         &lt;element name="climateRegions" type="{http://ipcc2006.air.sk/IPCC2006Export}climateRegions"/>
 *         &lt;element name="soilTypes" type="{http://ipcc2006.air.sk/IPCC2006Export}soilTypes"/>
 *         &lt;element name="forestLand" type="{http://ipcc2006.air.sk/IPCC2006Export}forestLand"/>
 *         &lt;element name="cropland" type="{http://ipcc2006.air.sk/IPCC2006Export}cropland"/>
 *         &lt;element name="grassland" type="{http://ipcc2006.air.sk/IPCC2006Export}grassland"/>
 *         &lt;element name="wetland" type="{http://ipcc2006.air.sk/IPCC2006Export}wetland"/>
 *         &lt;element name="settlement" type="{http://ipcc2006.air.sk/IPCC2006Export}settlement"/>
 *         &lt;element name="otherland" type="{http://ipcc2006.air.sk/IPCC2006Export}otherland"/>
 *         &lt;element name="landRepresentation" type="{http://ipcc2006.air.sk/IPCC2006Export}landRepresentation"/>
 *         &lt;element name="socRefTable" type="{http://ipcc2006.air.sk/IPCC2006Export}socRefTable"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "landTypes", propOrder = {
    "countryCode",
    "climateRegions",
    "soilTypes",
    "forestLand",
    "cropland",
    "grassland",
    "wetland",
    "settlement",
    "otherland",
    "landRepresentation",
    "socRefTable"
})
public class LandTypes {

    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected ClimateRegions climateRegions;
    @XmlElement(required = true)
    protected SoilTypes soilTypes;
    @XmlElement(required = true)
    protected ForestLand forestLand;
    @XmlElement(required = true)
    protected Cropland cropland;
    @XmlElement(required = true)
    protected Grassland grassland;
    @XmlElement(required = true)
    protected Wetland wetland;
    @XmlElement(required = true)
    protected Settlement settlement;
    @XmlElement(required = true)
    protected Otherland otherland;
    @XmlElement(required = true)
    protected LandRepresentation landRepresentation;
    @XmlElement(required = true)
    protected SocRefTable socRefTable;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the climateRegions property.
     * 
     * @return
     *     possible object is
     *     {@link ClimateRegions }
     *     
     */
    public ClimateRegions getClimateRegions() {
        return climateRegions;
    }

    /**
     * Sets the value of the climateRegions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClimateRegions }
     *     
     */
    public void setClimateRegions(ClimateRegions value) {
        this.climateRegions = value;
    }

    /**
     * Gets the value of the soilTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SoilTypes }
     *     
     */
    public SoilTypes getSoilTypes() {
        return soilTypes;
    }

    /**
     * Sets the value of the soilTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoilTypes }
     *     
     */
    public void setSoilTypes(SoilTypes value) {
        this.soilTypes = value;
    }

    /**
     * Gets the value of the forestLand property.
     * 
     * @return
     *     possible object is
     *     {@link ForestLand }
     *     
     */
    public ForestLand getForestLand() {
        return forestLand;
    }

    /**
     * Sets the value of the forestLand property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForestLand }
     *     
     */
    public void setForestLand(ForestLand value) {
        this.forestLand = value;
    }

    /**
     * Gets the value of the cropland property.
     * 
     * @return
     *     possible object is
     *     {@link Cropland }
     *     
     */
    public Cropland getCropland() {
        return cropland;
    }

    /**
     * Sets the value of the cropland property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cropland }
     *     
     */
    public void setCropland(Cropland value) {
        this.cropland = value;
    }

    /**
     * Gets the value of the grassland property.
     * 
     * @return
     *     possible object is
     *     {@link Grassland }
     *     
     */
    public Grassland getGrassland() {
        return grassland;
    }

    /**
     * Sets the value of the grassland property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grassland }
     *     
     */
    public void setGrassland(Grassland value) {
        this.grassland = value;
    }

    /**
     * Gets the value of the wetland property.
     * 
     * @return
     *     possible object is
     *     {@link Wetland }
     *     
     */
    public Wetland getWetland() {
        return wetland;
    }

    /**
     * Sets the value of the wetland property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wetland }
     *     
     */
    public void setWetland(Wetland value) {
        this.wetland = value;
    }

    /**
     * Gets the value of the settlement property.
     * 
     * @return
     *     possible object is
     *     {@link Settlement }
     *     
     */
    public Settlement getSettlement() {
        return settlement;
    }

    /**
     * Sets the value of the settlement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settlement }
     *     
     */
    public void setSettlement(Settlement value) {
        this.settlement = value;
    }

    /**
     * Gets the value of the otherland property.
     * 
     * @return
     *     possible object is
     *     {@link Otherland }
     *     
     */
    public Otherland getOtherland() {
        return otherland;
    }

    /**
     * Sets the value of the otherland property.
     * 
     * @param value
     *     allowed object is
     *     {@link Otherland }
     *     
     */
    public void setOtherland(Otherland value) {
        this.otherland = value;
    }

    /**
     * Gets the value of the landRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link LandRepresentation }
     *     
     */
    public LandRepresentation getLandRepresentation() {
        return landRepresentation;
    }

    /**
     * Sets the value of the landRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandRepresentation }
     *     
     */
    public void setLandRepresentation(LandRepresentation value) {
        this.landRepresentation = value;
    }

    /**
     * Gets the value of the socRefTable property.
     * 
     * @return
     *     possible object is
     *     {@link SocRefTable }
     *     
     */
    public SocRefTable getSocRefTable() {
        return socRefTable;
    }

    /**
     * Sets the value of the socRefTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocRefTable }
     *     
     */
    public void setSocRefTable(SocRefTable value) {
        this.socRefTable = value;
    }

}
