//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lrtLandSubcategory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lrtLandSubcategory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scatId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="remark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="landSubdivisions" type="{http://ipcc2006.air.sk/IPCC2006Export}lrtLandSubdivisions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lrtLandSubcategory", propOrder = {
    "scatId",
    "remark",
    "landSubdivisions"
})
public class LrtLandSubcategory {

    @XmlElement(required = true)
    protected Integer scatId;
    @XmlElement(required = true, nillable = true)
    protected String remark;
    @XmlElement(required = true)
    protected LrtLandSubdivisions landSubdivisions;

    /**
     * Gets the value of the scatId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScatId() {
        return scatId;
    }

    /**
     * Sets the value of the scatId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScatId(Integer value) {
        this.scatId = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the landSubdivisions property.
     * 
     * @return
     *     possible object is
     *     {@link LrtLandSubdivisions }
     *     
     */
    public LrtLandSubdivisions getLandSubdivisions() {
        return landSubdivisions;
    }

    /**
     * Sets the value of the landSubdivisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link LrtLandSubdivisions }
     *     
     */
    public void setLandSubdivisions(LrtLandSubdivisions value) {
        this.landSubdivisions = value;
    }

}
