//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lrtLandUnitHistoryRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lrtLandUnitHistoryRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ltIdPrev" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="cltIdPrev" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="transPeriod" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="convYear" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="remark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lrtLandUnitHistoryRecord", propOrder = {
    "ltIdPrev",
    "cltIdPrev",
    "transPeriod",
    "convYear",
    "remark"
})
public class LrtLandUnitHistoryRecord {

    @XmlElement(required = true)
    protected Integer ltIdPrev;
    @XmlElement(required = true)
    protected Integer cltIdPrev;
    @XmlElement(required = true)
    protected Integer transPeriod;
    @XmlElement(required = true)
    protected Integer convYear;
    @XmlElement(required = true, nillable = true)
    protected String remark;

    /**
     * Gets the value of the ltIdPrev property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLtIdPrev() {
        return ltIdPrev;
    }

    /**
     * Sets the value of the ltIdPrev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLtIdPrev(Integer value) {
        this.ltIdPrev = value;
    }

    /**
     * Gets the value of the cltIdPrev property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCltIdPrev() {
        return cltIdPrev;
    }

    /**
     * Sets the value of the cltIdPrev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCltIdPrev(Integer value) {
        this.cltIdPrev = value;
    }

    /**
     * Gets the value of the transPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransPeriod() {
        return transPeriod;
    }

    /**
     * Sets the value of the transPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransPeriod(Integer value) {
        this.transPeriod = value;
    }

    /**
     * Gets the value of the convYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConvYear() {
        return convYear;
    }

    /**
     * Sets the value of the convYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConvYear(Integer value) {
        this.convYear = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

}
