//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.22 at 11:25:06 AM CET 
//


package org.openforis.collect.earth.ipcc.serialize;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lrtLandCategory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lrtLandCategory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ltId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="remark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="landSubcategories" type="{http://ipcc2006.air.sk/IPCC2006Export}lrtLandSubcategories"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lrtLandCategory", propOrder = {
    "ltId",
    "remark",
    "landSubcategories"
})
public class LrtLandCategory {

    @XmlElement(required = true)
    protected Integer ltId;
    @XmlElement(required = true, nillable = true)
    protected String remark;
    @XmlElement(required = true)
    protected LrtLandSubcategories landSubcategories;

    /**
     * Gets the value of the ltId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLtId() {
        return ltId;
    }

    /**
     * Sets the value of the ltId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLtId(Integer value) {
        this.ltId = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the landSubcategories property.
     * 
     * @return
     *     possible object is
     *     {@link LrtLandSubcategories }
     *     
     */
    public LrtLandSubcategories getLandSubcategories() {
    	if( landSubcategories == null ) {
    		landSubcategories = new LrtLandSubcategories();
    	}
        return landSubcategories;
    }

    /**
     * Sets the value of the landSubcategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link LrtLandSubcategories }
     *     
     */
    public void setLandSubcategories(LrtLandSubcategories value) {
        this.landSubcategories = value;
    }

}
