//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//


package org.openforis.collect.earth.ipcc.serialize;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openforis.collect.earth.ipcc.serialize package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openforis.collect.earth.ipcc.serialize
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IPCC2006Export }
     * 
     */
    public IPCC2006Export createIPCC2006Export() {
        return new IPCC2006Export();
    }

    /**
     * Create an instance of {@link LrtLandUnit }
     * 
     */
    public LrtLandUnit createLrtLandUnit() {
        return new LrtLandUnit();
    }

    /**
     * Create an instance of {@link IPCC2006Export.Record }
     * 
     */
    public IPCC2006Export.Record createIPCC2006ExportRecord() {
        return new IPCC2006Export.Record();
    }

    /**
     * Create an instance of {@link LrtLandUnitHistory }
     * 
     */
    public LrtLandUnitHistory createLrtLandUnitHistory() {
        return new LrtLandUnitHistory();
    }

    /**
     * Create an instance of {@link CltGrassland }
     * 
     */
    public CltGrassland createCltGrassland() {
        return new CltGrassland();
    }

    /**
     * Create an instance of {@link CltSettlement }
     * 
     */
    public CltSettlement createCltSettlement() {
        return new CltSettlement();
    }

    /**
     * Create an instance of {@link LrtRegions }
     * 
     */
    public LrtRegions createLrtRegions() {
        return new LrtRegions();
    }

    /**
     * Create an instance of {@link LrtCountry }
     * 
     */
    public LrtCountry createLrtCountry() {
        return new LrtCountry();
    }

    /**
     * Create an instance of {@link SoilTypes }
     * 
     */
    public SoilTypes createSoilTypes() {
        return new SoilTypes();
    }

    /**
     * Create an instance of {@link LrtLandUnitArea }
     * 
     */
    public LrtLandUnitArea createLrtLandUnitArea() {
        return new LrtLandUnitArea();
    }

    /**
     * Create an instance of {@link LandRepresentation }
     * 
     */
    public LandRepresentation createLandRepresentation() {
        return new LandRepresentation();
    }

    /**
     * Create an instance of {@link Settlement }
     * 
     */
    public Settlement createSettlement() {
        return new Settlement();
    }

    /**
     * Create an instance of {@link ClimateRegion }
     * 
     */
    public ClimateRegion createClimateRegion() {
        return new ClimateRegion();
    }

    /**
     * Create an instance of {@link LrtLandUnits }
     * 
     */
    public LrtLandUnits createLrtLandUnits() {
        return new LrtLandUnits();
    }

    /**
     * Create an instance of {@link LandTypes }
     * 
     */
    public LandTypes createLandTypes() {
        return new LandTypes();
    }

    /**
     * Create an instance of {@link LrtLandSubcategory }
     * 
     */
    public LrtLandSubcategory createLrtLandSubcategory() {
        return new LrtLandSubcategory();
    }

    /**
     * Create an instance of {@link SoilType }
     * 
     */
    public SoilType createSoilType() {
        return new SoilType();
    }

    /**
     * Create an instance of {@link Cropland }
     * 
     */
    public Cropland createCropland() {
        return new Cropland();
    }

    /**
     * Create an instance of {@link CltWetland }
     * 
     */
    public CltWetland createCltWetland() {
        return new CltWetland();
    }

    /**
     * Create an instance of {@link LrtLandSubdivisions }
     * 
     */
    public LrtLandSubdivisions createLrtLandSubdivisions() {
        return new LrtLandSubdivisions();
    }

    /**
     * Create an instance of {@link Wetland }
     * 
     */
    public Wetland createWetland() {
        return new Wetland();
    }

    /**
     * Create an instance of {@link CltOtherland }
     * 
     */
    public CltOtherland createCltOtherland() {
        return new CltOtherland();
    }

    /**
     * Create an instance of {@link ForestLand }
     * 
     */
    public ForestLand createForestLand() {
        return new ForestLand();
    }

    /**
     * Create an instance of {@link LrtRegion }
     * 
     */
    public LrtRegion createLrtRegion() {
        return new LrtRegion();
    }

    /**
     * Create an instance of {@link LrtLandCategory }
     * 
     */
    public LrtLandCategory createLrtLandCategory() {
        return new LrtLandCategory();
    }

    /**
     * Create an instance of {@link LrtLandUnitHistoryRecord }
     * 
     */
    public LrtLandUnitHistoryRecord createLrtLandUnitHistoryRecord() {
        return new LrtLandUnitHistoryRecord();
    }

    /**
     * Create an instance of {@link CltForestLand }
     * 
     */
    public CltForestLand createCltForestLand() {
        return new CltForestLand();
    }

    /**
     * Create an instance of {@link CltCropland }
     * 
     */
    public CltCropland createCltCropland() {
        return new CltCropland();
    }

    /**
     * Create an instance of {@link Grassland }
     * 
     */
    public Grassland createGrassland() {
        return new Grassland();
    }

    /**
     * Create an instance of {@link ClimateRegions }
     * 
     */
    public ClimateRegions createClimateRegions() {
        return new ClimateRegions();
    }

    /**
     * Create an instance of {@link Otherland }
     * 
     */
    public Otherland createOtherland() {
        return new Otherland();
    }

    /**
     * Create an instance of {@link LrtLandSubdivision }
     * 
     */
    public LrtLandSubdivision createLrtLandSubdivision() {
        return new LrtLandSubdivision();
    }

    /**
     * Create an instance of {@link LrtLandCategories }
     * 
     */
    public LrtLandCategories createLrtLandCategories() {
        return new LrtLandCategories();
    }

    /**
     * Create an instance of {@link LrtLandSubcategories }
     * 
     */
    public LrtLandSubcategories createLrtLandSubcategories() {
        return new LrtLandSubcategories();
    }

    /**
     * Create an instance of {@link LrtLandUnit.Areas }
     * 
     */
    public LrtLandUnit.Areas createLrtLandUnitAreas() {
        return new LrtLandUnit.Areas();
    }

    /**
     * Create an instance of {@link LrtLandUnit.AreasA1D }
     * 
     */
    public LrtLandUnit.AreasA1D createLrtLandUnitAreasA1D() {
        return new LrtLandUnit.AreasA1D();
    }

}
