//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:52:33 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ipcc2006.air.sk/IPCC2006Export")
package org.openforis.collect.earth.ipcc.serialize;
