//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.22 at 11:25:06 AM CET 
//


package org.openforis.collect.earth.ipcc.serialize;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for socRefRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="socRefRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="climateRegionId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="soilTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="socRef" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "socRefRecord", propOrder = {
    "climateRegionId",
    "soilTypeId",
    "socRef"
})
public class SocRefRecord {

    @XmlElement(required = true)
    protected Integer climateRegionId;
    @XmlElement(required = true)
    protected Integer soilTypeId;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double socRef;

    /**
     * Gets the value of the climateRegionId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClimateRegionId() {
        return climateRegionId;
    }

    /**
     * Sets the value of the climateRegionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClimateRegionId(Integer value) {
        this.climateRegionId = value;
    }

    /**
     * Gets the value of the soilTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSoilTypeId() {
        return soilTypeId;
    }

    /**
     * Sets the value of the soilTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSoilTypeId(Integer value) {
        this.soilTypeId = value;
    }

    /**
     * Gets the value of the socRef property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSocRef() {
        return socRef;
    }

    /**
     * Sets the value of the socRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSocRef(Double value) {
        this.socRef = value;
    }

}
